worker-threads: 4
worker-fs-threads: 2
logger-level: info

is-testing: false

server-port: 8080

# change to URI of your postgres database
pg-connection: postgresql://testsuite@localhost:15433/paste_service_db_1

# change to URI of your mongo database
mongo-connection: mongodb://localhost:27217/admin