config_vars: /app/configs/config_vars.yaml

components_manager:
    task_processors:
        main-task-processor:
            worker_threads: $worker-threads
        fs-task-processor:
            worker_threads: $worker-fs-threads

    default_task_processor: main-task-processor

    components:
        server:
            listener:
                port: $server-port
                task_processor: main-task-processor

        logging:
            fs-task-processor: fs-task-processor
            loggers:
                default:
                    file_path: '@stderr'
                    level: $logger-level
                    overflow_behavior: discard

        dynamic-config:
            defaults:
                HTTP_CLIENT_CONNECTION_POOL_SIZE: 1000
                POSTGRES_DEFAULT_COMMAND_CONTROL:
                    network_timeout_ms: 750
                    statement_timeout_ms: 500

        blob-repo:
        metadata-repo:
        cache-purger: # purges nginx cache on paste DELETE
            load-enabled: $cache-purge-enabled # disabled in non-e2e tests
        paste-service:

        testsuite-support: {}

        congestion-control:
            only-rtc: false
            fake-mode: $is-testing

        tests-control:
            load-enabled: $is-testing
            path: /tests/{action}
            method: POST
            task_processor: main-task-processor

        handler-ping:
            path: /ping
            method: GET
            task_processor: main-task-processor
            throttling_enabled: false
            url_trailing_slash: strict-match

        handler-get-paste:
            path: /api/v1/{id}
            method: GET
            task_processor: main-task-processor

        handler-upload-paste:
            path: /api/v1/paste
            method: POST
            task_processor: main-task-processor
            max_request_size: 1049200 # ~1.0006MB

        handler-delete-paste:
            path: /api/v1/delete/{id}
            method: DELETE
            task_processor: main-task-processor
            max_request_size: 1024 # 1KB

        postgres-db-1:
            dbconnection: $pg-connection
            blocking_task_processor: fs-task-processor
            dns_resolver: async
            sync-start: true
            connlimit_mode: manual

        mongo-db-1:
            dbconnection: $mongo-connection