name: Build and optionally test a service

on:
  workflow_call:
    inputs:
      service-name:
        required: true
        type: string
      build-type:
        required: true
        type: string
        default: 'debug'
      run-tests:
        required: false
        type: boolean
        default: true
      run-in-docker:
        required: false
        type: boolean
        default: true
      upload-artifact:
        required: false
        type: string
        default: ""

jobs:
  build-test:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          submodules: true

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Cache Docker layers
        uses: actions/cache@v4
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-buildx-${{ inputs.service-name }}-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-buildx-${{ inputs.service-name }}-

      - name: Cache ccache directory
        uses: actions/cache@v4
        with:
          path: .ccache
          key: ccache-${{ inputs.service-name }}-${{ inputs.build-type }}-${{ github.ref }}-${{ github.run_number }}
          restore-keys: |
            ccache-${{ inputs.service-name }}-${{ inputs.build-type }}-${{ github.ref }}-
            ccache-${{ inputs.service-name }}-${{ inputs.build-type }}-

      - name: Fix run_as_user.sh permissions
        if: inputs.run-in-docker
        run: |
          [ -f run_as_user.sh ] && chmod +x run_as_user.sh || true
        working-directory: shared/

      - name: Build
        run: make ${{ inputs.run-in-docker && 'docker-' || '' }}build-${{ inputs.build-type }}
        working-directory: services/${{ inputs.service-name }}

      - name: Test
        if: inputs.run-tests && inputs.build-type == 'debug'
        run: make ${{ inputs.run-in-docker && 'docker-' || '' }}test-${{ inputs.build-type }} \
          DOCKER_EXTRA_OPTS="--security-opt seccomp=unconfined" \
          DOCKER_EXTRA_ENV="UBSAN_OPTIONS='print_stacktrace=1'"
          # --security-opt runs container in privileged mode
          # because otherwise StackUsageMonitor causes userver to SIGABRT in debug builds
        working-directory: services/${{ inputs.service-name }}

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        if: inputs.upload-artifact != ''
        with:
          name: ${{ inputs.service-name }}-binary
          path: services/${{ inputs.service-name }}/build-${{ inputs.build-type }}/${{ inputs.upload-artifact }}